# Generated by Django 5.0 on 2024-01-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portadasGym')),
                ('description', models.CharField(max_length=300)),
                ('days', models.CharField(max_length=200)),
                ('hour', models.CharField(max_length=200)),
                ('prof', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OldOutDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deport', models.CharField(max_length=100)),
                ('lugar_salida', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_evento', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OutDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_evento', models.CharField(max_length=100)),
                ('deport', models.CharField(max_length=100)),
                ('lugar_salida', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=1100)),
                ('short_description', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portadasOutDoor')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
